### PR TITLE
Pin pymongo compatibility, add maintainers

### LINKED ISSUE #17: The latest conda package (2.3.0) does not pin to pymongo<4.0
I had the following issue reported to motor today: [MOTOR-862](https://jira.mongodb.org/browse/MOTOR-862)

> Today, when I installed motor 2.3.0 with the command:
> ```
> conda install motor
> ```
> It also installed pymongo 4.0 that is incompatible with motor.
> It crashed with the following error:
> ```
> Traceback (most recent call last):
> ...
> File "/opt/conda/envs/doogle_server/lib/python3.9/site-packages/motor/__init__.py", line 35, in <module>
> from .motor_tornado import *
> File "/opt/conda/envs/doogle_server/lib/python3.9/site-packages/motor/motor_tornado.py", line 17, in <module>
> from . import core, motor_gridfs
> File "/opt/conda/envs/doogle_server/lib/python3.9/site-packages/motor/core.py", line 27, in <module>
> import pymongo.mongo_replica_set_client
> ModuleNotFoundError: No module named 'pymongo.mongo_replica_set_client'
> ```
> I solve it (as a workaround) by using the pipy package (2.5.0) that pinned the pymongo version
> ```
> pip install motor
> ```

I am not sure why it automatically pulls in PyMongo 4.0 because the motor 2.3.0 release correctly pins to pymongo >=3.11,<4: https://github.com/mongodb/motor/blob/2.3.0/setup.py#L32. Does conda install not respect version requirements in dependencies?

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #17 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
@ShaneHarvey please confirm you'd like to be added as a maintainer

**Review by ShaneHarvey — APPROVED** [review]

**Comment by blink1073** [comment]
cc @mariusvniekerk

**Comment by blink1073** [comment]
cc @conda-forge/core we'd like to pick up maintenance of this feedstock

**Comment by beckermr** [comment]
Resolve the conflicts and merge away @blink1073!

**Comment by blink1073** [comment]
Thanks @beckermr!

**Pull request merged**
