### PR TITLE
Manual bump to 2.3.0

### PR DESCRIPTION
**Pull request by crusaderky**
Aligned to https://motor.readthedocs.io/en/stable/requirements.html

### CODE REVIEW

**Comment by gimperiale** [comment]
@conda-forge-admin please rerender

**Comment by crusaderky** [comment]
@conda-forge-admin please rerender

**Comment by crusaderky** [comment]
@conda-forge-admin please rerender

**Comment by crusaderky** [comment]
@conda-forge-admin please rerender

**Comment by crusaderky** [comment]
@motor-feedstock-maintainers @hodgsonw ready for merge

**Comment by crusaderky** [comment]
@motor-feedstock ready for merge

**Comment by gimperiale** [comment]
@hodgsonw ping

**Pull request merged**
